### ISSUE TITLE
Why autoexec()?

### ISSUE THREAD

**Issue by teppyboy** [stangithuboffical/SirFork#1]
SirHurt already did that for you, if you do that then script will be executed twice...
Also the problem i noticed in my project is injected value is stored in-app so it won't save, then everytime you open the app it'll show Injected is false (even sirhurtui - offical ui)
I'm trying to fix that by save the value in registry but im too lazy xD

and are u sure u created the autoinject lmfao

**Comment by teppyboy** [comment]
and please do
                        ServicePointManager.ServerCertificateValidationCallback += new RemoteCertificateValidationCallback(AlwaysGoodCertificate);
                        ServicePointManager.Expect100Continue = true;
                        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
before download a string/file because windows 7 is cool

**Comment by stangithuboffical** [comment]
removing autoexec soon
